// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    userId: "userId"
  }
});

export default function() {
  postman[Request]({
    name: "Adding a user",
    id: "50b0dd5b-49de-495d-bd56-275bdb1c15ca",
    method: "POST",
    address: "https://gorest.co.in/public/v2/users",
    data:
      '{\r\n    "name": "Tenali Ramakrishna",\r\n    "gender": "male",\r\n    "email": "tenali.ramakrishna@151ce.com",\r\n    "status": "active"\r\n}',
    post(response) {
      const jsonData = pm.response.json();
      pm.collectionVariables.set("userId", jsonData.id);

      pm.test("Status code 201", function() {
        pm.response.to.have.status(201);
      });

      pm.test("valida email", function() {
        pm.expect(jsonData.email).to.be.eq("tenali.ramakrishna@151ce.com");
      });
    },
    auth(config, Var) {
      config.headers.Authorization =
        "Bearer 4b117ec1edd3b1f81a118745654730bbc05fa6fb1aa68cc51f792f55eca90822";
    }
  });

  postman[Request]({
    name: "Geting a user",
    id: "c3aa9380-af93-442c-9a54-174bd0b8da26",
    method: "GET",
    address: "https://gorest.co.in/public/v2/users",
    post(response) {
      pm.test("Status code 200", function() {
        pm.response.to.have.status(200);
      });
    },
    auth(config, Var) {
      config.headers.Authorization =
        "Bearer 4b117ec1edd3b1f81a118745654730bbc05fa6fb1aa68cc51f792f55eca90822";
    }
  });

  postman[Request]({
    name: "Updating a user",
    id: "11642498-8d8b-4a55-85ad-01b348993406",
    method: "PATCH",
    address: "https://gorest.co.in/public/v2/users/{{userId}}",
    data:
      '{\r\n    "name": "Allasani Peddana",\r\n    "email": "allasani.peddana@155ce.com",\r\n    "status": "active"\r\n}',
    post(response) {
      pm.test("Status code 200", function() {
        pm.response.to.have.status(200);
      });
    },
    auth(config, Var) {
      config.headers.Authorization =
        "Bearer 4b117ec1edd3b1f81a118745654730bbc05fa6fb1aa68cc51f792f55eca90822";
    }
  });

  postman[Request]({
    name: "Delete a user",
    id: "dd471745-f66c-4ecb-80dc-814b686da7cf",
    method: "DELETE",
    address: "https://gorest.co.in/public/v2/users/{{userId}}",
    post(response) {
      pm.test("Status code 204", function() {
        pm.response.to.have.status(204);
      });
    },
    auth(config, Var) {
      config.headers.Authorization =
        "Bearer 4b117ec1edd3b1f81a118745654730bbc05fa6fb1aa68cc51f792f55eca90822";
    }
  });
}
